### ISSUE TITLE
win的、空格、中文路径、处理极度拉跨，根本用不了

### ISSUE THREAD

**Issue by 2522595153** [kunwu2023/kunwu#1]

**Comment by ctccaozhe** [comment]
是gui还是cli版本的问题呀，cli版本的路径处理目前是已知问题，gui版本内部测试路径是没有问题的

**Comment by 2522595153** [comment]
gui

**Comment by 2522595153** [comment]
貌似都用不了

**Comment by cncert** [comment]
啥也没有。。

**Comment by ctccaozhe** [comment]
【已修复】
空格、中文路径问题已修复
![图片](https://github.com/kunwu2023/kunwu/assets/66074614/2adabc16-d66a-4be8-8fcf-f9412a2e91e9)
