### ISSUE TITLE
When can open source detection related code logic be available?

### ISSUE THREAD

**Issue by chennqqi** [kunwu2023/kunwu#3]
The current code only has an interface for HTTP upload detection. Upload code detection has data security concerns.

**Comment by ctccaozhe** [comment]
Hello,

Thank you very much for your interest in our project and for your question. Regarding your inquiry about the availability of open source detection related code logic, we deeply understand your interest and needs. Indeed, the current version only provides an interface for HTTP upload detection, and we acknowledge your concerns about data security in relation to code upload detection.

We highly value feedback from community members and are very concerned about data security issues. Ensuring the security of user data is one of our top priorities. Therefore, the opening of certain code logics and functionalities requires thorough review and assessment to ensure that no potential data security risks are introduced.

Regarding the part of your question about the engine, it's true that internal plans for open-sourcing parts of the engine are still under careful consideration and planning. We are actively exploring the best methods and practices to, in the future, share more code and logic with the community while ensuring security.

We greatly appreciate your understanding and patience. Please continue to follow our project updates, as we look forward to sharing more progress and results in the future.

Thank you again for your support and understanding.

Best regards.

**Comment by ctccaozhe** [comment]
If there are concerns about data security,we offer a compiled version with an offline detection engine available for download in the releases section.
